# This is a basic workflow to help you get started with Actions

name: lint
on: push
jobs:
  my_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - name: dependency setting
        run: make install
        
      - name: eslint chek
        run: make lint
