# This is a basic workflow to help you get started with Actions

name: lint
on:
  push:
    branches: [ main ]
    
jobs:
  my_job:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Dependency setting
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
