# This is a basic workflow to help you get started with Actions

name: lint
on: push
jobs:
  my_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: make install
      - run: make lint
